# Generated by Django 3.0 on 2022-04-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chairman', '0006_auto_20220421_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=30)),
                ('job_specifications', models.CharField(max_length=50)),
                ('job_address', models.TextField(max_length=500)),
                ('birthdate', models.CharField(max_length=15)),
                ('no_of_members', models.CharField(max_length=50)),
                ('marrital_status', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Indian', max_length=15)),
                ('gender', models.CharField(max_length=20)),
                ('no_of_vehicles', models.CharField(default='', max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('id_proof', models.FileField(default='media/default.png', upload_to='media/documents')),
                ('profile_pic', models.FileField(default='media/default.png', upload_to='media/images')),
                ('house_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.House')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.User')),
            ],
        ),
    ]
