# Generated by Django 3.0 on 2022-04-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman', '0006_auto_20220421_1707'),
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_proof',
            field=models.FileField(default='media/default.png', upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.FileField(default='media/default.png', upload_to='media/images/'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('videofile', models.FileField(null=True, upload_to='media/videos/', verbose_name='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.User')),
            ],
        ),
    ]
