# Generated by Django 3.0 on 2022-04-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_auto_20220423_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='user_id',
        ),
    ]
