# Generated by Django 3.0 on 2022-04-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_remove_notice_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='videofile',
            field=models.FileField(null=True, upload_to='media/videos/', verbose_name='video'),
        ),
        migrations.CreateModel(
            name='NoticeView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.Member')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.Notice')),
            ],
        ),
    ]
