# Generated by Django 3.0 on 2022-04-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_auto_20220427_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('videofile', models.FileField(null=True, upload_to='media/videos/', verbose_name='video')),
            ],
        ),
    ]
