# Generated by Django 3.0 on 2022-04-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.Event')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.Member')),
            ],
        ),
    ]
