# Generated by Django 3.0 on 2022-04-29 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman', '0006_auto_20220421_1707'),
        ('Member', '0006_eventview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('videofile', models.FileField(null=True, upload_to='media/videos/', verbose_name='video')),
                ('house_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.House')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventview',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventview',
            name='member_id',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventView',
        ),
    ]
