# Generated by Django 3.0 on 2022-04-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0008_event_eventview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventview',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventview',
            name='member_id',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventView',
        ),
    ]
