# Generated by Django 3.0 on 2022-04-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0010_event_eventview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='eventview',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventview',
            name='member_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/', verbose_name='video'),
        ),
    ]
