# Generated by Django 3.0 on 2022-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0013_event_eventview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='videofile',
            field=models.FileField(null=True, upload_to='media/videos/', verbose_name='video'),
        ),
    ]
