# Generated by Django 3.0 on 2022-04-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0014_auto_20220429_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
    ]
