# Generated by Django 3.0 on 2022-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0015_remove_event_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
