# Generated by Django 3.0 on 2022-04-25 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chairman', '0006_auto_20220421_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('id_proof', models.FileField(default='media/default.png', upload_to='media/images')),
                ('profile_pic', models.FileField(default='media/default.png', upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.User')),
            ],
        ),
    ]
