# Generated by Django 3.0 on 2022-04-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseno', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=30)),
                ('job_specifications', models.CharField(max_length=50)),
                ('job_address', models.TextField(max_length=500)),
                ('birthdate', models.CharField(max_length=15)),
                ('no_of_members', models.CharField(max_length=50)),
                ('marrital_status', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Indian', max_length=15)),
                ('gender', models.CharField(max_length=20)),
                ('no_of_vehicles', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('id_proof', models.FileField(default='media/default.png', upload_to='media/documents')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.House')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=11)),
                ('profile_pic', models.FileField(default='media/default.png', upload_to='media/images')),
                ('gender', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.User')),
            ],
        ),
    ]
