# Generated by Django 3.0 on 2022-04-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='house_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Chairman',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
