# Generated by Django 3.0 on 2022-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman', '0003_chairman_house_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='no_of_vehicles',
        ),
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.FileField(default='media/default.png', upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_time_login',
            field=models.BooleanField(default=False),
        ),
    ]
