# Generated by Django 3.0 on 2022-04-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman', '0005_member_no_of_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
